import type { BiomeDefinition } from '../../../types';

export const MEDIEVAL_BIOMES: BiomeDefinition[] = [
    { id: 'tavern', label: 'Tavern', color: '#8b6914', registry: 'medieval' },
    { id: 'castle', label: 'Castle', color: '#7a7a7a', registry: 'medieval' },
    { id: 'fortress', label: 'Fortress', color: '#5c5c5c', registry: 'medieval' },
    { id: 'farm', label: 'Farm', color: '#a0b040', registry: 'medieval' },
    { id: 'dirt_road', label: 'Dirt Road', color: '#9e8c6c', registry: 'medieval' },
    { id: 'outhouse', label: 'Outhouse', color: '#7a6040', registry: 'medieval' },
    { id: 'barn', label: 'Barn', color: '#8b4513', registry: 'medieval' },
    { id: 'ranch', label: 'Ranch', color: '#a08050', registry: 'medieval' },
    { id: 'brothel', label: 'Brothel', color: '#8b1a4a', registry: 'medieval' },
    { id: 'marketplace', label: 'Marketplace', color: '#c8a030', registry: 'medieval' },
    { id: 'guard_tower', label: 'Guard Tower', color: '#6a6a7a', registry: 'medieval' },
    { id: 'windmill', label: 'Windmill', color: '#b0a080', registry: 'medieval' },
    { id: 'monastery', label: 'Monastery', color: '#8a806a', registry: 'medieval' },
    { id: 'bridge', label: 'Bridge', color: '#6e5a3a', registry: 'medieval' },
    { id: 'fishing_village', label: 'Fishing Village', color: '#5a8a8a', registry: 'medieval' },
    { id: 'mine', label: 'Mine', color: '#4a4a4a', registry: 'medieval' },
    { id: 'lumber_camp', label: 'Lumber Camp', color: '#5a7a3a', registry: 'medieval' },
    { id: 'watchtower', label: 'Watchtower', color: '#7a7a8a', registry: 'medieval' },
    { id: 'blacksmith', label: 'Blacksmith', color: '#3a3a3a', registry: 'medieval' },
    { id: 'stable', label: 'Stable', color: '#7a6a4a', registry: 'medieval' },
    { id: 'granary', label: 'Granary', color: '#b0a060', registry: 'medieval' },
    { id: 'well', label: 'Well', color: '#4a6a8a', registry: 'medieval' },
    { id: 'gallows', label: 'Gallows', color: '#5a4a3a', registry: 'medieval' },
    { id: 'shrine', label: 'Shrine', color: '#9a8a7a', registry: 'medieval' },
    { id: 'wagon_camp', label: 'Wagon Camp', color: '#8a7a50', registry: 'medieval' },
];
