import type { BiomeDefinition } from '../../../types';

export const NATURE_BIOMES: BiomeDefinition[] = [
    { id: 'forest', label: 'Forest', color: '#2d5a27', registry: 'nature' },
    { id: 'dense_forest', label: 'Dense Forest', color: '#1a3d18', registry: 'nature' },
    { id: 'plains', label: 'Plains', color: '#7cba5f', registry: 'nature' },
    { id: 'mountain', label: 'Mountain', color: '#6b6b6b', registry: 'nature' },
    { id: 'hills', label: 'Rolling Hills', color: '#8fa87e', registry: 'nature' },
    { id: 'river', label: 'River', color: '#3b7dd8', registry: 'nature' },
    { id: 'coast', label: 'Coast', color: '#c2b280', registry: 'nature' },
    { id: 'cliff', label: 'Cliff', color: '#5a5a5a', registry: 'nature' },
    { id: 'flower_field', label: 'Flower Field', color: '#d4a0d4', registry: 'nature' },
    { id: 'snow_tundra', label: 'Snow Tundra', color: '#dce8f0', registry: 'nature' },
    { id: 'lava_field', label: 'Lava Field', color: '#8b2500', registry: 'nature' },
    { id: 'desert_dunes', label: 'Desert Dunes', color: '#d4b86a', registry: 'nature' },
    { id: 'oasis', label: 'Oasis', color: '#4da6a6', registry: 'nature' },
    { id: 'canyon', label: 'Canyon', color: '#a0522d', registry: 'nature' },
    { id: 'swamp', label: 'Swamp', color: '#4a5e3a', registry: 'nature' },
    { id: 'lake', label: 'Lake', color: '#4682b4', registry: 'nature' },
    { id: 'volcanic_peak', label: 'Volcanic Peak', color: '#4a1a1a', registry: 'nature' },
    { id: 'glacier', label: 'Glacier', color: '#b0d4e8', registry: 'nature' },
    { id: 'beach', label: 'Beach', color: '#e8d68e', registry: 'nature' },
    { id: 'deep_ocean', label: 'Deep Ocean', color: '#1a3c6e', registry: 'nature' },
    { id: 'shallow_sea', label: 'Shallow Sea', color: '#3a7ec2', registry: 'nature' },
    { id: 'reef', label: 'Coral Reef', color: '#2e8b8b', registry: 'nature' },
    { id: 'rainforest', label: 'Rainforest', color: '#1a6b2a', registry: 'nature' },
    { id: 'savanna', label: 'Savanna', color: '#b8a44a', registry: 'nature' },
    { id: 'steppe', label: 'Steppe', color: '#a8b060', registry: 'nature' },
    { id: 'bog', label: 'Bog', color: '#3d4a2a', registry: 'nature' },
    { id: 'mangrove', label: 'Mangrove', color: '#2a6e3a', registry: 'nature' },
    { id: 'atoll', label: 'Atoll', color: '#5ec4c4', registry: 'nature' },
    { id: 'fjord', label: 'Fjord', color: '#4a7a9a', registry: 'nature' },
];
